config_view:
  name: Config
  view: yes
  entities:
    - group.automation_motion
    - group.automation_lights
    - group.automation_locks
    - group.automation_presence
    - group.automation_notification
    - automation.run_office_filter
